export enum SCREENS {
  ROOT="ROOT",
  HOME = "Home",
  SUPPORT = "Support",
  INTRO = "INTRO",
  PROFILE = "PROFILE",
  PROFILE_STACK = "PROFILE_STACK",
  PROFILE_INFO = "PROFILE_INFO",
  PROFILE_EDIT = "PROFILE_EDIT",
  PROFILE_TRANSACTION = "PROFILE_TRANSACTION",
  PROFILE_CHANGE_PHONE='PROFILE_CHANGE_PHONE',
  SCANNER = "SCANNER",
  FAQ_ITEM = "FAQ_ITEM",
  SHOPS = "SHOPS",
  NEWS_ITEM = "NEWS_ITEM",
  PRODUCT_SCREEN = "PRODUCT_SCREEN",
  HISTORY_NEWS = "HISTORY_NEWS",
  PHONE_CHANGE = "PHONE_CHANGE",
  PRODUCT_CATEGORY = "PRODUCT_CATEGORY",
  HISTORY_PURCHASES = "HISTORY_PURCHASES",
  
  //AUTH
  AUTHORIZATION_SMS = "AUTHORIZATION_SMS",
  AUTHORIZATION_PHONE = "AUTHORIZATION_PHONE",
  AUTHORIZATION_FORM='AUTHORIZATION_FORM',
  //STACK
  AUTHORIZATION_STACK = "AUTHORIZATION_STACK",
  HOME_STACK = "HOME_STACK",
}
